include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Core rules
    - always_declare_return_types
    - always_use_package_imports
    - annotate_overrides
    - avoid_print
    - avoid_relative_lib_imports
    - camel_case_types
    - constant_identifier_names
    - depend_on_referenced_packages
    - directives_ordering
    - file_names
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_single_quotes
    - require_trailing_commas
    - type_annotate_public_apis
    - unnecessary_const
    - unnecessary_this
    - use_key_in_widget_constructors

    # Optional stricter rules
    - avoid_dynamic_calls
    - avoid_function_literals_in_foreach_calls
    - prefer_expression_function_bodies
    - sort_child_properties_last
    - sort_constructors_first