include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "*/.g.dart"
    - "*/.freezed.dart"
    - "*/.mappable.dart"
    - "*/.gen.dart"
    - "*/.gr.dart"
    - "*/.config.dart"